## Google Music Media Player
## Use this 'package.yaml' file to configure "gmusic_player"
media_player:
  - platform: gmusic_player
    device_id: !secret gmusic_device_id
    username: !secret gmusic_username
    password: !secret gmusic_password
      
    ## Add your media_players below
    speakers: # Example media_players
      - bedroom_stereo
      - workshop_stereo
      
    ## Optional: enable streaming from gmusicproxy (Workaround for issue #6)
    ## https://github.com/tprelog/homeassistant-gmusic_player/issues/6
    #gmusicproxy: !secret gmusic_proxy
